### PR TITLE
fix: corrupted mac installation from jc admin console deployment script

### PR DESCRIPTION
**Pull request by aassafjc**
## Issues
* [NB-10865](https://jumpcloud.atlassian.net/browse/NB-10865) - [JC AGENT] DA app installed from JC's admin console deployment script is being corrupted on macOS

## What does this solve?
DA app installed from JC's admin console deployment script is being corrupted on macOS

## Is there anything particularly tricky?
No

## How should this be tested?
**Prerequisites:**
1- macOS machine (preferably macOS Sonoma)

**Testing steps:**
1- Take the command from `Powershell/JumpCloud Commands Gallery/Mac Commands/Mac - Install JumpCloud Password Manager App.md`
2- Create a file on your machine and name it whatever you want but the extension should be `.sh`. e.g: `example.sh`
3- Paste the command you copied in step 1 in the `.sh` file you created in step 2
4- Open your terminal and go to the directory where the `.sh` file you created in step 2 can be found
5- Run `chmod 777 <scriptFileName>.sh` or `sudo chmod 777 <scriptFileName>.sh` depending on your situation
6- Run `./<scriptFileName>.sh`
7- After step 6 finishes execution, an app will show on your desktop. Double click it and see if the app opens successfully.

## Screenshots
N/A

[NB-10865]: https://jumpcloud.atlassian.net/browse/NB-10865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jworkmanjc** [comment]
Hey @aassafjc, 

I pushed one commit and changed your labels for this PR, I don't have documentation changes anywhere to create a proper PR to command gallery requests yet, we just updated our gitub actions workflow. I'll get a chance to test this after my morning meetings. 

@kmaranionjc would you also review this today? 

Thanks,
Joe

**Comment by kmaranionjc** [comment]
> ## Issues
> * [NB-10865](https://jumpcloud.atlassian.net/browse/NB-10865) - [JC AGENT] DA app installed from JC's admin console deployment script is being corrupted on macOS
> 
> ## What does this solve?
> DA app installed from JC's admin console deployment script is being corrupted on macOS
> 
> ## Is there anything particularly tricky?
> No
> 
> ## How should this be tested?
> **Prerequisites: Mac Machine**
> 
> 1- Take the command from `Powershell/JumpCloud Commands Gallery/Mac Commands/Mac - Install JumpCloud Password Manager App.md` 2- Create a file on your machine and name it whatever you want but the extension should be `.sh`. e.g: `example.sh` 3- Paste the command you copied in step 1 in the `.sh` file you created in step 2 4- Open your terminal and go to the directory where the `.sh` file you created in step 2 can be found 5- Run `chmod 777 <scriptFileName>.sh` or `sudo chmod 777 <scriptFileName>.sh` depending on your situation 6- Run `./<scriptFileName>.sh` 7- After step 6 finishes execution, an app will show on your desktop. Double click it and see if the app opens successfully.
> 
> ## Screenshots
> N/A

**Comment by kmaranionjc** [comment]
> ## Issues
> * [NB-10865](https://jumpcloud.atlassian.net/browse/NB-10865) - [JC AGENT] DA app installed from JC's admin console deployment script is being corrupted on macOS
> 
> ## What does this solve?
> DA app installed from JC's admin console deployment script is being corrupted on macOS
> 
> ## Is there anything particularly tricky?
> No
> 
> ## How should this be tested?
> **Prerequisites: Mac Machine**
> 
> 1- Take the command from `Powershell/JumpCloud Commands Gallery/Mac Commands/Mac - Install JumpCloud Password Manager App.md` 2- Create a file on your machine and name it whatever you want but the extension should be `.sh`. e.g: `example.sh` 3- Paste the command you copied in step 1 in the `.sh` file you created in step 2 4- Open your terminal and go to the directory where the `.sh` file you created in step 2 can be found 5- Run `chmod 777 <scriptFileName>.sh` or `sudo chmod 777 <scriptFileName>.sh` depending on your situation 6- Run `./<scriptFileName>.sh` 7- After step 6 finishes execution, an app will show on your desktop. Double click it and see if the app opens successfully.
> 
> ## Screenshots
> N/A

Hi @aassafjc, ran the command, it seemed like the new change is throwing permission error on my side, 
image
Current script ran just fine. I'm thinking `mv` may not be preserving the permissions during move?

**Comment by jworkmanjc** [comment]
> > ## Issues
> > 
> > * [NB-10865](https://jumpcloud.atlassian.net/browse/NB-10865) - [JC AGENT] DA app installed from JC's admin console deployment script is being corrupted on macOS
> > 
> > ## What does this solve?
> > DA app installed from JC's admin console deployment script is being corrupted on macOS
> > ## Is there anything particularly tricky?
> > No
> > ## How should this be tested?
> > **Prerequisites: Mac Machine**
> > 1- Take the command from `Powershell/JumpCloud Commands Gallery/Mac Commands/Mac - Install JumpCloud Password Manager App.md` 2- Create a file on your machine and name it whatever you want but the extension should be `.sh`. e.g: `example.sh` 3- Paste the command you copied in step 1 in the `.sh` file you created in step 2 4- Open your terminal and go to the directory where the `.sh` file you created in step 2 can be found 5- Run `chmod 777 <scriptFileName>.sh` or `sudo chmod 777 <scriptFileName>.sh` depending on your situation 6- Run `./<scriptFileName>.sh` 7- After step 6 finishes execution, an app will show on your desktop. Double click it and see if the app opens successfully.
> > ## Screenshots
> > N/A
> 
> Hi @aassafjc, ran the command, it seemed like the new change is throwing permission error on my side, image Current script ran just fine. I'm thinking `mv` may not be preserving the permissions during move?

I can confirm I'm seeing the same thing as @kmaranionjc

**Comment by aassafjc** [comment]
Thank you for your feedback! @jworkmanjc @kmaranionjc 

I'll try to reproduce the error you shared on my machine. I'll get back to you with a fix hopefully.

**Comment by aassafjc** [comment]
Hello @jworkmanjc and @kmaranionjc,

We fixed the issue that you faced in your last review: `Read-only file system`

@gbitarjc found out that the shortcut created by the script is not being removed and is not overwritten by the script when the script re-runs; which makes the old non-overwritten created shortcut pointing to a "damaged" DMG.

We also reverted from `mv` to `cp -pPR` and we tested our changes on both macOS Sonoma and macOS Ventura.

Let me know if these changes work for you!

Thank you,
Antoine

**Comment by jworkmanjc** [comment]
Hey @aassafjc , I just saw this, I'll review this tomorrow when I have my physical mac to test this on!

**Review by kmaranionjc — APPROVED** [review]
New change is working and fixed the issue. Thanks @aassafjc !

**Comment by aassafjc** [comment]
Thank you for your review @jworkmanjc @kmaranionjc!

What are the next steps to be taken to merge this branch to `master` and to deploy the fix?

**Comment by kmaranionjc** [comment]
> Thank you for your review @jworkmanjc @kmaranionjc!
> 
> What are the next steps to be taken to merge this branch to `master` and to deploy the fix?

@aassafjc merge the PR and you're all set

**Pull request merged**
